name       : fdk-aac
version    : 0.1.5
release    : 1
source     :
    - https://downloads.sourceforge.net/project/opencore-amr/fdk-aac/fdk-aac-0.1.5.tar.gz : 2164592a67b467e5b20fdcdaf5bd4c50685199067391c6fcad4fa5521c9b4dd7
license    : BSD-3-Clause
component  : multimedia.codecs
summary    : Fraunhofer FDK AAC codec library.
description: |
    Fraunhofer FDK AAC codec library.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
