name       : fdk-aac
version    : 0.1.6
release    : 2
source     :
    - https://downloads.sourceforge.net/project/opencore-amr/fdk-aac/fdk-aac-0.1.6.tar.gz : aab61b42ac6b5953e94924c73c194f08a86172d63d39c5717f526ca016bed3ad
license    : BSD-3-Clause
component  : multimedia.codecs
summary    : Fraunhofer FDK AAC codec library
description: |
    Library of OpenCORE Framework implementation of Adaptive Multi Rate
    Narrowband and Wideband (AMR-NB and AMR-WB) speech codec. Library of
    VisualOn implementation of Adaptive Multi Rate Wideband (AMR-WB) encoder
    and Advanced Audio Coding (AAC) encoder. Modified library of Fraunhofer
    AAC decoder and encoder.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
