name       : fdk-aac
version    : 0.1.6
release    : 3
source     :
    - https://github.com/mstorsjo/fdk-aac/archive/v0.1.6.tar.gz : adbcd793e406e1b88b3c1c41382d49f8c27371485b823c0fdab69c9124fd2ce3
license    : BSD-3-Clause
component  : multimedia.codecs
summary    : Fraunhofer FDK AAC codec library
description: |
    Library of OpenCORE Framework implementation of Adaptive Multi Rate
    Narrowband and Wideband (AMR-NB and AMR-WB) speech codec. Library of
    VisualOn implementation of Adaptive Multi Rate Wideband (AMR-WB) encoder
    and Advanced Audio Coding (AAC) encoder. Modified library of Fraunhofer
    AAC decoder and encoder.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
