name       : fdk-aac
version    : 2.0.0
release    : 4
source     :
    - https://sourceforge.net/projects/opencore-amr/files/fdk-aac/fdk-aac-2.0.0.tar.gz/download : f7d6e60f978ff1db952f7d5c3e96751816f5aef238ecf1d876972697b85fd96c
license    : BSD-3-Clause
component  : multimedia.codecs
summary    : Fraunhofer FDK AAC codec library
description: |
    Library of OpenCORE Framework implementation of Adaptive Multi Rate
    Narrowband and Wideband (AMR-NB and AMR-WB) speech codec. Library of
    VisualOn implementation of Adaptive Multi Rate Wideband (AMR-WB) encoder
    and Advanced Audio Coding (AAC) encoder. Modified library of Fraunhofer
    AAC decoder and encoder.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
