name       : fdk-aac
version    : 2.0.2
release    : 6
source     :
    - https://github.com/mstorsjo/fdk-aac/archive/refs/tags/v2.0.2.tar.gz : 7812b4f0cf66acda0d0fe4302545339517e702af7674dd04e5fe22a5ade16a90
license    : BSD-3-Clause
component  : multimedia.codecs
summary    : Fraunhofer FDK AAC codec library
description: |
    Library of OpenCORE Framework implementation of Adaptive Multi Rate Narrowband and Wideband (AMR-NB and AMR-WB) speech codec. Library of VisualOn implementation of Adaptive Multi Rate Wideband (AMR-WB) encoder and Advanced Audio Coding (AAC) encoder. Modified library of Fraunhofer AAC decoder and encoder.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
