name       : fdk-aac
version    : 2.0.1
release    : 5
source     :
    - https://github.com/mstorsjo/fdk-aac/archive/v2.0.1.tar.gz : a4142815d8d52d0e798212a5adea54ecf42bcd4eec8092b37a8cb615ace91dc6
license    : BSD-3-Clause
component  : multimedia.codecs
summary    : Fraunhofer FDK AAC codec library
description: |
    Library of OpenCORE Framework implementation of Adaptive Multi Rate
    Narrowband and Wideband (AMR-NB and AMR-WB) speech codec. Library of
    VisualOn implementation of Adaptive Multi Rate Wideband (AMR-WB) encoder
    and Advanced Audio Coding (AAC) encoder. Modified library of Fraunhofer
    AAC decoder and encoder.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
